services:
  products-db:
    image: mongo
    ports: 
      - "27018:27017"
    volumes:
      - products-data:/data/db

  auth-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - auth-data:/data/db

  products-service:
    build: ./backend/products-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_URL: mongodb://products-db:27017/test_db
      AUTH_SERVICE_URL: http://auth-service:3001
    depends_on:
      - products-db

  auth-service:
    build: ./backend/auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_URL: mongodb://auth-db:27017/test_auth
      JWT_SECRET: secretcualquiera
    depends_on:
      - auth-db

volumes:
  products-data:
  auth-data: